### ISSUE TITLE
Creates 5 buffers!

### ISSUE THREAD

**Issue by theunraveler** [mikewest/vimroom#1]
I really like the idea of this plugin. However, when I toggle Vimroom, it creates 5 different buffers. I'm guessing that you are doing this in order to get the spacing correct, but it really is a pain to close 5 different buffers when I actually want to quit vim.

Might this be a problem with something in my vimrc? Or are you experiencing this too? Is it by design?

**Comment by mikewest** [comment]
It actually only creates 4 buffers.  :)

I don't know of any other mechanism to get the spacing correct in a window of arbitrary size; I think the buffers are the only way to make it work the way I'd like it to work.

With regard to closing vim, you've got two options: either toggle vimroom before you close (which closes the extra buffers for you), or close with `:qa` rather than `:q`.  `:qa` will quit _all_ open buffers in one go, which works pretty well with something like this.

**Comment by theunraveler** [comment]
Ah! That works. Thanks for the suggestions.
